@API_HostAddress = http://localhost:5003

### 1. Lấy danh sách 
GET {{API_HostAddress}}/api/Product/List
Accept: application/json

### 2. Lấy category 
GET {{API_HostAddress}}/api/Product/GetCategories
Accept: application/json

### 3. Lấy chi tiết theo ID (Query string)
GET {{API_HostAddress}}/api/Product/GetByID?id=1
Accept: application/json
### 4. lấy supplier 
GET {{QLBH.API_HostAddress}}/api/Product/GetSuppliers
Accept: application/json

### 5. Lấy list customers
GET {{QLBH.API_HostAddress}}/api/Customer/List
Accept: application/json


### 6. Tạo mới sản phẩm
POST {{API_HostAddress}}/api/Product/Create
Content-Type: application/json

{
  "name": "Nho",
  "Price": 12000,
  "Quantity": " 12kg",
  "CateId": 1,
  "SupId": 1
  
}

###

### 7. Xóa sản phẩm
DELETE {{API_HostAddress}}/api/Product/Delete?Id=97